### ISSUE TITLE
question, hs-miner mines only HNS, to create a TLD on handshake is necessary to use that HNS for buying them. Right?

### ISSUE THREAD

**Issue by sam-smart-byte** [handshake-org/hs-miner#30]

**Comment by pinheadmz** [comment]
You must have some HNS to bid on auctions on-chain. I suppose if someone already owns a HNS TLD they can sell it to your for BTC or USD, but you will still need HNS to update the DNS records for that domain name (or do anything with it on chain, since all transactions require some kind of miner fee).

hs-miner "only" mines HNS, yes.

**Comment by sam-smart-byte** [comment]
@pinheadmz thank you!
